name: Destroy Development Environment

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "destroy" to confirm'
        required: true
        default: ''

env:
  AWS_REGION: us-east-1
  PROJECT_NAME: three-tier-app

jobs:
  destroy:
    name: Destroy Development Infrastructure
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_destroy == 'destroy'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
      
      - name: Terraform Init
        run: |
          cd terraform
          terraform init
      
      - name: Terraform Destroy
        run: |
          cd terraform
          terraform destroy \
            -var="environment=dev" \
            -var="notification_email=${{ secrets.NOTIFICATION_EMAIL }}" \
            -auto-approve
      
      - name: Clean up ECR images
        run: |
          # Delete all images in ECR repository
          aws ecr batch-delete-image \
            --repository-name ${{ env.PROJECT_NAME }}-backend \
            --image-ids "$(aws ecr list-images --repository-name ${{ env.PROJECT_NAME }}-backend --query 'imageIds[*]' --output json)" \
            --region ${{ env.AWS_REGION }} || true
