name: Security Scan

on:
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Monday at 2 AM
  workflow_dispatch:

env:
  PROJECT_NAME: infraprime

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
      
      - name: Run Bandit (Python security linter)
        run: |
          pip install bandit
          bandit -r application/backend/src/ -f json -o bandit-report.json
      
      - name: Run ESLint security scan
        run: |
          cd application/frontend
          npm install
          npm audit --audit-level=high
      
      - name: Scan Docker images
        run: |
          cd application/backend
          docker build -t infraprime-backend:security-scan .
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy image --exit-code 1 --severity HIGH,CRITICAL \
            infraprime-backend:security-scan
      
      - name: Upload security scan results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: security-scan-results
          path: |
            bandit-report.json
            trivy-results.sarif
